# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0966b05ffcb5ea8176bd0e4b7a0909b9bcc6f224a765bd87c6827caf6448617509fd5c3133046b184e4ea38afc4dab2af34bf3d7a333fadfb7a45f7762c8a88

test:
  secret_key_base: febe628c0d1ce382e17171f752f9d93a615fd5bfc3c1afbad0f371dcd47da7c66d22950ff523f31861ecfa512e39bf3463ede9e7001407cabad0618657d24358

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
