# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc1b5d585e38f9d0805c618a3396bc830c5c812389c3638c0f9d73da3119c4e32aa46d0763092b135643f3bd6522102750463e14b081668d004f345f8df0a8a0

test:
  secret_key_base: f12b170342fe80645858cf9ab29f31d7cc26cd2f4998cc8f6c606962e234c7c7462450da194d3bce4fc39a1898c954c37cdf4546765f2abfc314e79a12586487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
