# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c82dedd96843ec2c327937f99c37973103623b11d63c1f64bc4805265f2bc8de688f15db1902e30a4f2022fc933c2a6f6b0adf59705c3393a1065f31e58f52a

test:
  secret_key_base: 2a4956e403277dd2f6102f9e30e8eb9c549583ff16d131a990ccd89821d7f2bb35ba8390d47c4d86e4479fd248947b797773f52f6a2f1006e29446fbf91857f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
